packages:
  - 'packages/*'
  - 'packages/routing-sdk/**'
  - 'apps/*'
  - 'apis/*'
  - 'examples/*'
  - 'scripts'

catalog:
  viem: ^2.21.22
  wagmi: ^2.12.17
  next: 15.0.2
  wrangler: 3.81.0
  '@aptos-labs/ts-sdk': 1.30.0
